### ISSUE TITLE
Not worked bpl

### ISSUE THREAD

**Issue by ghost** [KazanExpress/mantha#1]
Hello,

just started to review what is it and first of all, not working structure of the project. When you click download on github **.webpack.config** folder not visible when unzip on MacOS(not tested with terminal). Best practice from my side rename to **build** folder which will contain webpack & rollup plugin. 

Not fully configured **webpack.base.ts**. It has deps 
```ts
import htmlConfigFactory from '../src/.config/build/html';
import chunkSplitPatterns from '../src/.config/build/chunk';
```
and those file are not presented(**.config** folder) at all. Better to move those file in build folder with other deps or in root but it's only my opinion. 

In documentation mentioned that less pug configuration but i only found Stylus(In this case need to change documentation)

Thanks for ts webpack BPL example

**Comment by kaskar2008** [comment]
Sorry for taking it so long. Repo has been updated. Closing the issue
