### ISSUE TITLE
Single File component in Vue

### ISSUE THREAD

**Issue by a-ajlouni10** [KazanExpress/mantha#5]
Im trying to add ag-grid-vue to the application but its not showing the data. I assume that its a compatibility issue with pug and stylus and typescript? If so how can i write a single file vue and render it in the application without writing pug and stylus?

**Comment by Raiondesu** [comment]
Hello, @a-ajlouni10.
Mantha is not currently well-suited for SFCs (single-file components).
You could add vue-loader to the config yourself, it's [not that hard to do](https://vue-loader.vuejs.org/guide/).

Pure `CSS` is still supported in `stylus`, so there's that.

---

A side note:\
Mantha was designed specifically to disallow SFCs, as they too easily become hard-to-maintain in large projects and tend to quickly grow in size and complexity.\
Instead - separation of concerns, maximum code-splitting and usage of [composition-api](https://github.com/vuejs/composition-api) is encouraged.

As for third-party SFCs - their place is in node_modules, as bundled `.js` (not `.vue`) files.

**Comment by Raiondesu** [comment]
I'm closing this issue as it's not an issue, but a question.
Discussion can still be continued here.

**Comment by Raiondesu** [comment]
@a-ajlouni10, by the way, we are currently developing the v2 of mantha, which would allow easier customization on this topic.
